autoload -Uz compinit
zmodload zsh/complist

# Moves zcompdump to cache directory
compinit -d "$XDG_CACHE_HOME/zsh/zcompdump"

# Sets types of completion to use
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate

# Enables menu selection for completion
zstyle ':completion:*' menu select

# Disables using deprecated compctl
zstyle ':completion:*' use-compctl false

# Enables completion caching for faster startup
zstyle ':completion:*' use-cache true
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/zcompcache"

# Sets colors for autocompletion options
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Autocompletion options for specific commands
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
zstyle ':completion:*:*:cp:*' file-sort modification
zstyle ':completion:*:*:chown:*' file-list all
zstyle ':completion:*:*:chmod:*' file-list all
# Taken from oh-my-zsh taskwarrior plugin
zstyle ':completion:*:*:task:*' verbose yes
zstyle ':completion:*:*:task:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:*:task:*' group-name ''

# Adds more descriptiveness to completion output
zstyle ':completion:*' verbose true

# Show dotfiles in completion
zstyle ':completion:*' file-patterns '%p(D):globbed-files *(D-/):directories' '*(D):all-files'

# These were generated by compinstall; not certain what they do.
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' glob 1
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' rehash true
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' list-suffixes true
