# Whether to install zsh and neovim plugins
plugins = true
# Whether to enable colemak rebinds
colemak = true

# Whether to enable zsh completion
zshcomp = true
# Whether to enable zsh abbeviations
zshabbr = true

# TODO
# Whether this machine is a laptop (tries to reduce power consumption)
laptop = true
# Whether this machine needs to use a GUI
graphical = true
# Whether you're using a tiling WM (changes terminal emulator)
sway = true
# Whether to use exclusively neovim
neovim = true
# What app should be used for MANPAGER (less, most, or nvim)
manpager = "less"
# Whether to include configs for programs I no longer use
legacy = false
