# Whether to install zsh and neovim plugins
plugins = true
# Whether to enable colemak rebinds
colemak = true

# Whether to enable zsh completion
zshcomp = true
# Whether to enable zsh abbeviations
zshabbr = true

# Whether to automatically start tmux with zsh
tmux = false

# Whether to use exclusively neovim
neovim = true
# Which terminal emulator to use
term = "alacritty"
# Whether this machine needs to use a GUI
graphical = true

# What app should be used for MANPAGER (less, most, or nvim)
manpager = "less"

# Whether you're using a tiling WM (disables kitty window decorations)
tiling = true

# TODO
# Whether this machine is a laptop (tries to reduce power consumption)
laptop = true
