# Whether to install zsh and neovim plugins
nvimplugins = false
zshplugins = false
# Whether to enable colemak rebinds
colemak = true

# Whether to use fish
fish = false
# Whether to enable zsh completion
zshcomp = true
# Whether to enable zsh abbeviations
zshabbr = true

# Whether to automatically start tmux with zsh
tmux = false

# Which EDITOR to use
editor = "nvim"

# What app should be used for MANPAGER (less, most, or nvim)
manpager = "less"

# Whether to download my preferred fonts
fonts = false
# What font size to use
fontsize = "12"
# Font to use for terminal emulators
termfont = "0xProto Nerd Font Mono"
# Font to use for desktop
deskfont = "CodeNewRoman Nerd Font Mono"
# Font to use for everything else
normfont = "Questrial"

# Whether to use a desktop
graphical = false
# Whether to use sway
sway = false
# Which terminal emulator to use
term = ""
